name: CI

on: [push, pull_request]

jobs:
  ubuntu-16_04:
    name: ubuntu-16_04
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - name: Build Linux
        run: docker build -f Linux.Dockerfile .
      - name: Vulnerability test (Linux)
        run: docker build -f Linux.Vulnerable.Dockerfile .

  windows-latest:
    name: windows-latest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Windows
        run: docker build -f Windows.Dockerfile .
      - name: Vulnerability test (Windows)
        run: docker build -f Windows.Vulnerable.Dockerfile .
